debug: false
server:
  hostname: localhost
  port: 8080
  ssl: false
  gql_introspection: true
  origins:
    - http://localhost:8080
    - http://localhost:3000
database:
  username: cble
  password: cble
  host: 127.0.0.1
  ssl: false
providers:
  cache: "/tmp/cble-providers"
auth:
  jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  session_timeout: 1440 # 24 hours * 60 mins
initialization:
  default_admin:
    first_name: CBLE
    last_name: Admin
    username: cble
    password: cble
  admin_group: CBLE Administrators
